attribute float particlePhase;
attribute vec3 particleDirection;
attribute float particleSpeedRandom;
attribute float particleFrictionRandom;
attribute float particleDurationRandom;
uniform float particleSpeed;
uniform float particleSpeedRandomness;
uniform float particleFrictionRandomness;
uniform float particleFriction;
uniform float particleDuration;
uniform float particleDurationRandomness;
uniform float size;
const float resolution = 800.0;
